config/routes.rb
Rails.application.routes.draw do
  resources :follows
  get "/search", to: "posts#search"
  get "/request_list", to: "follows#request"
  get "/send_friend_request", to: "users#send_friend_request"
  get "/accept_friend_request", to: "users#send_friend_request"
  get "/delete_friend_request", to: "users#delete_friend_request"
  get "/cancel_friend_request", to: "users#cancel_friend_request"
  resources :posts

  devise_for :users
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "Post", optional: true
  has_many :posts, foreign_key: :parent_id

  def is_friend_post(current_user)
    begin
      current_user.followees.find(self.user_id)
      return true
    rescue
      return false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :followed_users, foreign_key: :follower_id, class_name: "Follow"
  has_many :followees, through: :followed_users

  has_many :following_users, foreign_key: :followee_id, class_name: "Follow"
  has_many :followers, through: :following_users

  def not_following
    @following = self.followees
    @users = User.all
    @not_following = @users - @following
  end

  def friend_request_list
    @wating_request = self.followers - self.followees
    return @wating_request
  end

  def friend_status(friend_id)
    begin
      self.followees.find(friend_id)
      check_is_friend(friend_id)
    rescue
      return "not followed"
    end
  end

  def is_friend(current_user)
    begin
      if current_user.followees.find(self.id) && current_user.followers.find(self.id)
        return true
      end
    rescue
      return false
    end
  end

  private

  def check_is_friend(friend_id)
    begin
      User.find(friend_id).followees.find(self.id)
      return "friend"
    rescue
      return "not friend"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:nickname, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:nickname, :email, :password, :current_password) }
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ new show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @nicknameList = []
    @posts.each do |post|
      nickname = User.find(post.user_id).nickname
      @nicknameList << nickname
    end
  end

  def search
    @parameters = params[:query].downcase
    if !@parameters.blank?
      puts " userrrrrr #{current_user.id}"
      @search_user = User.all.where("id <> #{current_user.id} and lower(nickname) LIKE '%#{@parameters}%'")
    else
      @search_user = User.all.where("id <> #{current_user.id}")
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @parent_id = params[:post]
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    puts "paramsss #{post_params}"
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :index, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    if params[:id].nil?
      return
    end
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :user_id, :parent_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # followees người mình theo dõi
  # followers người theo dõi mình
  def send_friend_request
    @user = User.find(params[:id])
    @user.followers << current_user
    redirect_back(fallback_location: root_path)
  end

  def delete_friend_request
    @follower = current_user.followers.delete(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def accept_friend_request
    @followee = User.find(params[:id])
    current_user.followers << @followee
    redirect_back(fallback_location: root_path)
  end

  def cancel_friend_request
    current_user.followees.delete(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def remove_friend_request
    @request = Follow.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/_sidebar.html.erb
<div class="wrapper search-wrapper">
  <div class="shortcuts search-shortcuts">
    <div class="second-col search-col">
      <h6 class="title">
        Search results
      </h6>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/friends.png', alt: ""%>
          </div>
          <h4>Home </h4>
        </div>
      </div>
      <div class="menu-item active">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/request.png', alt: ""%>
          </div>
          <h4>Friend requests </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/add_friend.png', alt: ""%>
          </div>
          <h4>Suggestions </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/friends.png', alt: ""%>
          </div>
          <h4>All friends </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/gift-box-with-a-bow.png', alt: ""%>
          </div>
          <h4>Birthdays </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'posts/friends.png', alt: ""%>
          </div>
          <h4>Custom list </h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/follows/request.html.erb
<div class="app-container">
  <!--navbar-->
  <%= render "home/navbar"%>
  <!--content-->
  <%= render "posts/sidebar"%>
  <div class="friend-list">
    <h4>
      Friend requests
    </h4>
    <div class="detail-list">
      <% current_user.friend_request_list.each do |user| %>
        <div class="profile">
          <%= image_tag 'avatar/unknown.jpeg', alt: "", class: 'avatar'%>
          <h4><%= user.nickname %></h4>
          <div class="button-area">
            <%= link_to 'Confirm', accept_friend_request_path(:id => user.id), class: 'confirm'%>
            <%= link_to 'Delete', delete_friend_request_path(:id => user.id), class: 'delete'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_dialog.html.erb
<div id="dialog-menu">
  <ul>
    <% if user_signed_in? %>
      <li class="dialog-menu-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/_navbar.html.erb
<nav>
  <!--logo and search-->
  <div class="left-side">
    <div class="logo">
      <%= link_to image_tag('icons/facebook.svg', alt: ""), root_path%>
    </div>
    <%= form_with url: search_path, method: :get do |form| %>
      <div class="search">
        <%= form.text_field :query %>
        <%= image_tag 'posts/search.png', alt: "", class: "search-icon"%>
        <%= form.submit "Search"%>
      </div>
    <%end%>
  </div>
  <div class="btn-group">
  </div>
  <!--tab icons-->
  <div class="tabs">
    <div class="tab-icon active">
      <div class="icon">
        <%= image_tag 'icons/home.svg', alt: ""%>
      </div>
    </div>
    <div class="tab-icon">
      <div class="icon has-notification">
        <%= image_tag 'icons/flag.svg', alt: ""%>
      </div>
    </div>
    <div class="tab-icon">
      <div class="icon">
        <%= image_tag 'icons/tv.svg', alt: ""%>
      </div>
    </div>
    <div class="tab-icon">
      <div class="icon">
        <%= image_tag 'icons/users.svg', alt: ""%>
      </div>
    </div>
    <div class="tab-icon">
      <div class="icon has-notification">
        <%= image_tag 'icons/calendar.svg', alt: ""%>
      </div>
    </div>
  </div>
  <!--right side-->
  <div class="right-side">
    <div class="user">
      <div class="profile">
        <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
      </div>
      <h4><%= current_user.nickname %></h4>
    </div>
    <!--icons-->
    <div class="user-icons">
      <div class="icon">
        <%= image_tag 'icons/plus.svg', alt: ""%>
      </div>
      <div class="icon has-notification">
        <%= image_tag 'icons/messenger.svg', alt: ""%>
      </div>
      <div class="icon">
        <%= image_tag 'icons/bell.svg', alt: ""%>
      </div>
      <div class="icon" id="nav-dialog">
        <%= image_tag 'icons/arrow.svg', alt: ""%>
        <%= render 'home/dialog'%>
      </div>
    </div>
  </div>
</nav>

<script>
  let navDiv;
  let navMenu;

  setTimeout(() => {
    navDiv = document.getElementById("nav-dialog");
    navMenu = document.getElementById("dialog-menu");
    navDiv.onclick = () => {
      if (navMenu.style.display !== "none") {
        navMenu.style.display = "none";
      } else {
        navMenu.style.display = "block";
      }
    };
  }, 1);
</script>

app/views/home/index.html.erb
This is index page

app/views/layouts/_arlerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert" id="alert-message">
  <%= notice %>
</div>
<script>
  setTimeout(() => {
    alertMess = document.getElementById("alert-message");
    alertMess.style.display = "none"
    // alertMess.style.display = "block"
  }, 2000)
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= favicon_link_tag 'https://www.linkpicture.com/q/facebook_36.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag('index.js') %>
    <%= javascript_include_tag('jquery.js') %>
    <%= javascript_include_tag('owlCarrousel.js') %>
  </head>
  <body>
    <% if notice %>
      <%= render 'layouts/arlerts'%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: posts_path) do |form| %>
  <div>
    <%= form.text_area :content, placeholder: "What are you thinking?" %>
    <%= form.number_field :user_id, id: :post_user_id,  value: current_user.id, type: "hidden"%>
    <%= form.number_field :parent_id, id: :parent_id,  value: @parent_id, type: "hidden"%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/_sidebar.html.erb
<div class="wrapper search-wrapper">
  <div class="shortcuts search-shortcuts">
    <div class="second-col search-col">
      <h6 class="title">
        Search results
      </h6>
      <div class="menu-item active">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/feed.png', alt: ""%>
          </div>
          <h4>All </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/post.png', alt: ""%>
          </div>
          <h4>Posts </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/friends.png', alt: ""%>
          </div>
          <h4>People </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/image.png', alt: ""%>
          </div>
          <h4>Photos </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/youtube.png', alt: ""%>
          </div>
          <h4>Videos </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/retail.png', alt: ""%>
          </div>
          <h4>Marketplace </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/report.png', alt: ""%>
          </div>
          <h4>Pages </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/place.png', alt: ""%>
          </div>
          <h4>Places </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/group.png', alt: ""%>
          </div>
          <h4>Groups </h4>
        </div>
      </div>
      <div class="menu-item">
        <div class="item-row">
          <div class="icon icon-second">
            <%= image_tag 'search/event.png', alt: ""%>
          </div>
          <h4>Events </h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="app-container">
  <!--navbar-->
  <%= render "home/navbar"%>
  <!--content-->
  <div class="wrapper">
    <div class="shortcuts">
      <div class="first-col">
        <div class="menu-item">
          <div class="user">
            <div class="profile">
              <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
            </div>
            <h4><%= current_user.nickname %></h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'icons/shield.svg', alt: ""%>
            </div>
            <h4>COVID-19 Information </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <%= link_to image_tag('icons/colored-people.svg', alt: "") + 'Friends', request_list_path%>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'icons/colored-messenger.svg', alt: ""%>
            </div>
            <h4>Messenger </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'icons/colored-flag.svg', alt: ""%>
            </div>
            <h4>Pages </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row  border">
            <div class="icon more">
              <%= image_tag 'icons/arrow-down.svg', alt: ""%>
            </div>
            <h4>see more </h4>
          </div>
        </div>
      </div>
      <div class="second-col">
        <h6 class="title">
          your shortcuts
        </h6>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'stories/st-1.jpeg', alt: ""%>
            </div>
            <h4>Designers house </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'stories/st-2.jpeg', alt: ""%>
            </div>
            <h4>Script house </h4>
          </div>
          <div class="menu-item">
            <div class="item-row">
              <div class="icon">
                <%= image_tag 'stories/page-1.jpg', alt: ""%>
              </div>
              <h4>ui ux Designers workshop </h4>
            </div>
          </div>
          <div class="menu-item">
            <div class="item-row">
              <div class="icon">
                <%= image_tag 'stories/st-3.jpeg', alt: ""%>
              </div>
              <h4>netflix movies recommends </h4>
            </div>
          </div>
          <div class="menu-item">
            <div class="item-row">
              <div class="icon">
                <%= image_tag 'stories/page-2.jpg', alt: ""%>
              </div>
              <h4>the future </h4>
            </div>
          </div>
          <div class="menu-item">
            <div class="item-row">
              <div class="icon">
                <%= image_tag 'stories/page-3.jpeg', alt: ""%>
              </div>
              <h4> smart </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--posts-->
    <div class="posts">
      <!--create post-->
      <div class="timeline">
        <div class="view create-post">
          <div class="input">
            <div class="user">
              <div class="profile">
                <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
              </div>
            </div>
            <%= link_to 'Bạn đang nghĩ gì', new_post_path, class: "open-post-link" %>
          </div>
          <div class="media">
            <div class="category">
              <div class="option">
                <div class="icon">
                  <%= image_tag 'icons/video-live.svg', alt: ""%>
                </div>
                <span>Live video</span>
              </div>
              <div class="option">
                <div class="icon">
                  <%= image_tag 'icons/photos.svg', alt: ""%>
                </div>
                <span>photo/video</span>
              </div>
              <div class="option">
                <div class="icon">
                  <%= image_tag 'icons/smile.svg', alt: ""%>
                </div>
                <span>feeling/activity</span>
              </div>
            </div>
          </div>
        </div>
        <!--post container-->
        <% @posts.reverse.each do |post| %>
          <% if  post.user == current_user && post.parent_id.nil? || post.is_friend_post(current_user)%>
            <div class="view view-post-container smaller-margin">
              <div class="view-post">
                <div class="upper">
                  <div class="d-flex">
                    <div class="user">
                      <div class="profile">
                        <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
                      </div>
                    </div>
                    <div class="info">
                      <h6 class="name">
                        <%= @nicknameList[@posts.find_index(post)] %>
                      </h6>
                      <span class="time">1 hour ago</span>
                    </div>
                  </div>
                  <div class="dots">
                    <div class="dot"></div>
                  </div>
                </div>
                <div class="desc">
                  <p><%= post.content%></p>
                </div>
                <div class="actions-container">
                  <div class="action">
                    <div class="icon">
                      <%= image_tag 'icons/thumbs-up.svg', alt: ""%>
                    </div>
                    <span>
                      Like
                    </span>
                  </div>
                  <div class="action">
                    <div class="icon">
                      <%= image_tag 'icons/comment.svg', alt: ""%>
                    </div>
                    <span>
                      Comment
                    </span>
                  </div>
                  <div class="action">
                    <div class="icon">
                      <%= image_tag 'icons/share.svg', alt: ""%>
                    </div>
                    <span>
                      Share
                    </span>
                  </div>
                </div>
                <div class="comment-list">
                  <% @posts.reverse.each do |comment| %>
                    <% if comment.parent_id == post.id%>
                      <div class="comment-box">
                        <div class="user">
                          <div class="profile">
                            <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
                          </div>
                        </div>
                        <div class="comment-content">
                          <h4><%= @nicknameList[@posts.find_index(comment)] %></h4>
                          <p><%= comment.content%></p>
                        </div>
                      </div>
                      <%# <div class="input">
                        <%= link_to 'Write your comment ... ', new_post_path(:post => comment), class: "open-post-link"%>
                      <%# </div> %>
                    <%end%>
                  <% end %>
                </div>
                <div class="write-comment">
                  <div class="user">
                    <div class="profile">
                      <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
                    </div>
                  </div>
                  <div class="input">
                    <%= link_to 'Write your comment ... ', new_post_path(:post => post), class: "open-post-link"%>
                    <div class="media">
                      <div class="icon">
                        <%= image_tag 'icons/camera.svg', alt: ""%>
                      </div>
                      <div class="icon">
                        <%= image_tag 'icons/image.svg', alt: ""%>
                      </div>
                      <div class="icon">
                        <%= image_tag 'icons/smile-2.svg', alt: ""%>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!--shortcuts 2 -events and chat- -->
    <div class="shortcuts shortcuts-2">
      <div class="second-col first-col">
        <div class="menu-item">
          <div class="upper">
            <h6>Your pages</h6>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'stories/st-2.jpeg', alt: ""%>
            </div>
            <h4>Script house </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon">
              <%= image_tag 'stories/st-1.jpeg', alt: ""%>
            </div>
            <h4>Bibs ui design </h4>
          </div>
        </div>
        <div class="menu-item">
          <div class="item-row  border">
            <div class="icon more">
              <%= image_tag 'icons/arrow-down.svg', alt: ""%>
            </div>
            <h4>see more </h4>
          </div>
        </div>
      </div>
      <div class="second-col">
        <h6 class="title">
          birthdays
        </h6>
        <div class="menu-item">
          <div class="item-row">
            <div class="icon not-rounded">
              <%= image_tag 'icons/gift.svg', alt: ""%>
            </div>
            <h4>It's Diana Berry's birthday </h4>
          </div>
        </div>
        <div class="online">
          <h6 class="title">
            contact
          </h6>
          <% current_user.followees.each do |friend|%>
            <% if friend.is_friend(current_user)%>
              <div class="user">
                <div class="profile">
                  <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
                </div>
                <h4><%= friend.nickname %></h4>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<!-- <h1>New post</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div> -->
<div class="new-post">
  <div class="create-post-area">
      <div class="title">
        Share your feeling
      </div>
      <div class="input-field">
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="app-container">
  <!--navbar-->
  <%= render "home/navbar"%>
  <!--content-->
  <%= render "posts/sidebar"%>
</div>
<!--posts-->
<div class="posts search-list">
  <div class="timeline">
    <div class="view view-post-container smaller-margin">
      <div class="wrapper">
        <div class="shortcuts shortcuts-2">
          <div class="second-col">
            <div class="online search-online">
              <h6 class="title search-title">
                People
              </h6>
              <% @search_user.each do |user| %>
                <div class="user search-user">
                  <div class="profile">
                    <%= image_tag 'avatar/unknown.jpeg', alt: ""%>
                  </div>
                  <h4><%= user.nickname %>
                  </h4>
                  <% if current_user.friend_status(user.id) == "friend"%>
                    <div class="friend-follow">
                      <%= image_tag 'posts/messenger.png', alt: "" %>
                    </div>
                  <% elsif current_user.friend_status(user.id) == "not followed" %>
                    <div class="friend-follow">
                      <%= image_tag 'posts/add_friend.png', alt: "" %>
                      <%= link_to "Add", send_friend_request_path(:id => user.id)%>
                    </div>
                  <% else %>
                    <div class="friend-follow">
                      <%= image_tag 'posts/delete_request.png', alt: "" %>
                      <%= link_to "Delete", cancel_friend_request_path(:id => user.id)%>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>